"""initial_schema_schedule_planner

Revision ID: 25f1e2c68cb2
Revises: 
Create Date: 2026-03-26 17:01:20.965556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f1e2c68cb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DIRECTOR', name='user_role', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('school_code', sa.String(length=50), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DATA_LOADED', 'GENERATED', 'VALIDATED', 'EXPORTED', name='project_status', create_constraint=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_key'), 'projects', ['key'], unique=True)
    op.create_table('business_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('MAX_CONSECUTIVE_HOURS', 'NO_SAME_SUBJECT_TWICE_DAY', 'TEACHER_MAX_DAILY_HOURS', 'SUBJECT_PREFERRED_SLOT', 'SECTION_FREE_PERIOD', 'CUSTOM', name='business_rule_type', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_hard', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rules_project_id'), 'business_rules', ['project_id'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSED', 'VALIDATED', 'ERROR', name='import_status', create_constraint=True), nullable=False),
    sa.Column('row_counts', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('imported_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_imports_project_id'), 'data_imports', ['project_id'], unique=False)
    op.create_table('schedule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'VALIDATED', 'EXPORTED', name='schedule_status', create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('GENERATED', 'MANUAL_EDIT', 'ASSISTANT_EDIT', name='schedule_source', create_constraint=True), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('shift', sa.Enum('MORNING', 'AFTERNOON', name='shift_enum'), nullable=False),
    sa.Column('conflicts_count', sa.Integer(), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['schedule_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', 'shift', name='uq_schedule_version_project_number_shift')
    )
    op.create_index(op.f('ix_schedule_versions_project_id'), 'schedule_versions', ['project_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('shift', sa.Enum('MORNING', 'AFTERNOON', name='shift_enum'), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('opcion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'grade', 'code', 'shift', name='uq_section_project_grade_code_shift')
    )
    op.create_index(op.f('ix_sections_project_id'), 'sections', ['project_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_remediation', sa.Boolean(), nullable=False),
    sa.Column('parent_subject_id', sa.UUID(), nullable=True),
    sa.Column('requires_consecutive', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_subject_project_code')
    )
    op.create_index(op.f('ix_subjects_project_id'), 'subjects', ['project_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('nip', sa.String(length=50), nullable=True),
    sa.Column('dui', sa.String(length=50), nullable=True),
    sa.Column('id_persona', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('shift', sa.Enum('MORNING', 'AFTERNOON', name='shift_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'nip', name='uq_teacher_project_nip')
    )
    op.create_index(op.f('ix_teachers_project_id'), 'teachers', ['project_id'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_order', sa.Integer(), nullable=False),
    sa.Column('shift', sa.Enum('MORNING', 'AFTERNOON', name='shift_enum'), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 4', name='ck_timeslot_day_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'day_of_week', 'start_time', 'shift', name='uq_timeslot_project_day_start_shift')
    )
    op.create_index(op.f('ix_time_slots_project_id'), 'time_slots', ['project_id'], unique=False)
    op.create_table('assistant_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('schedule_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_conversations_project_id'), 'assistant_conversations', ['project_id'], unique=False)
    op.create_table('grade_subject_loads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'grade', 'subject_id', name='uq_grade_subject_load')
    )
    op.create_index(op.f('ix_grade_subject_loads_project_id'), 'grade_subject_loads', ['project_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('conflict_flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', 'section_id', 'time_slot_id', name='uq_entry_version_section_slot')
    )
    op.create_index(op.f('ix_schedule_entries_schedule_version_id'), 'schedule_entries', ['schedule_version_id'], unique=False)
    op.create_table('teacher_availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'time_slot_id', name='uq_teacher_availability')
    )
    op.create_index(op.f('ix_teacher_availabilities_project_id'), 'teacher_availabilities', ['project_id'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('section_code', sa.String(length=50), nullable=True),
    sa.Column('preference_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'grade', 'section_code', name='uq_teacher_subject_grade_section')
    )
    op.create_index(op.f('ix_teacher_subjects_project_id'), 'teacher_subjects', ['project_id'], unique=False)
    op.create_table('assistant_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('proposed_actions', sa.JSON(), nullable=True),
    sa.Column('actions_applied', sa.Boolean(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_messages_conversation_id'), 'assistant_messages', ['conversation_id'], unique=False)
    op.create_table('schedule_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_version_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Enum('ASSIGN', 'REASSIGN', 'SWAP', 'REMOVE', 'LOCK', 'UNLOCK', name='change_type', create_constraint=True), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('previous_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assistant_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['assistant_messages.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['schedule_entries.id'], ),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_changes_schedule_version_id'), 'schedule_changes', ['schedule_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_changes_schedule_version_id'), table_name='schedule_changes')
    op.drop_table('schedule_changes')
    op.drop_index(op.f('ix_assistant_messages_conversation_id'), table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_index(op.f('ix_teacher_subjects_project_id'), table_name='teacher_subjects')
    op.drop_table('teacher_subjects')
    op.drop_index(op.f('ix_teacher_availabilities_project_id'), table_name='teacher_availabilities')
    op.drop_table('teacher_availabilities')
    op.drop_index(op.f('ix_schedule_entries_schedule_version_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_grade_subject_loads_project_id'), table_name='grade_subject_loads')
    op.drop_table('grade_subject_loads')
    op.drop_index(op.f('ix_assistant_conversations_project_id'), table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    op.drop_index(op.f('ix_time_slots_project_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_teachers_project_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_project_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_sections_project_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_schedule_versions_project_id'), table_name='schedule_versions')
    op.drop_table('schedule_versions')
    op.drop_index(op.f('ix_data_imports_project_id'), table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_index(op.f('ix_business_rules_project_id'), table_name='business_rules')
    op.drop_table('business_rules')
    op.drop_index(op.f('ix_projects_key'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
